### ISSUE TITLE
Check availability of lxml

### ISSUE THREAD

**Issue by fgeek** [gbrindisi/xsssniper#6]
Currently if mechanize is missing xsssniper will say:
```
[X] Please install mechanize module:
    http://wwwsearch.sourceforge.net/mechanize/
```
But if lxml is missing it will say:
```
Traceback (most recent call last):
  File "xsssniper.py", line 6, in <module>
    from core.engine import Engine
  File "/home/hsalo/xsssniper/core/engine.py", line 24, in <module>
    from core.domscanner import DOMScanner
  File "/home/hsalo/xsssniper/core/domscanner.py", line 11, in <module>
    from lxml import etree
ImportError: No module named lxml
```
Maybe xsssniper should also give pip install -commands rather than per project URLs, but that is design decision.

**Comment by gbrindisi** [comment]
I think it's just been a bad design decision.
Nowadays I'd like more to put a `requirements.txt` and have the user go trough it to met the dependencies.

**Comment by fgeek** [comment]
Yes. Using requirements.txt is a good option and if "Please install x module" is used then there should be same mechanism for all components. General stacktrace when module is missing is pretty obvious too.. I can create a pull request for requirements.txt change.

**Comment by tholu** [comment]
Using requirements.txt is a good way for this I would say.

@gbrindisi Are you still actively maintaining this project?

**Comment by gbrindisi** [comment]
I am not actively developing, but I can review and merge pull requests :+1:

**Comment by tholu** [comment]
@gbrindisi Thanks for your quick answer, packaging/releasing/publishing it for pip (#2) would be the next best thing to increase usage and pull requests.

**Comment by gbrindisi** [comment]
@tholu I will put this in my backlog

**Comment by mtechmycourse** [comment]
Traceback (most recent call last):
  File "xss1.py", line 7, in <module>
    from core.target import Target
ImportError: No module named core.target

**Comment by mtechmycourse** [comment]
Yes, I successfully get the output of the project Thank you.
